version: '3.8'

networks:
  frontend_net:
    driver: overlay
    attachable: true
  gw_auth_net:
    driver: overlay
  gw_bl_net:
    driver: overlay
  gw_adminer_net:
    driver: overlay
  backend_auth_net:
    driver: overlay
  backend_routes_net:
    driver: overlay
  backend_bl_net:
    driver: overlay
  adminer:
    driver: overlay


volumes:
  db_data:

services:
  db:
    image: andreistan26/database:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin  # Test
      POSTGRES_PASSWORD: password123 # Test
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_routes_net
      - backend_auth_net
      - adminer
    #deploy:
      #placement:
        #constraints: [node.role == manager]

  auth-app:
    image: andreistan26/auth-service:latest
    networks:
      - gw_auth_net
      - backend_auth_net
    #deploy:
      #replicas: 2
      #placement:
        #constraints: [node.role == worker]

  kong:
    image: andreistan26/kong:latest
    ports:
      - target: 8022     # Testing port
        published: 8022
        protocol: tcp
        mode: host
      - 8000:8000
      - 8001:8001
    networks:
      - frontend_net
      - gw_auth_net
      - gw_bl_net
      - gw_adminer_net
    #deploy:
      #placement:
        #constraints: [node.role == manager]

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - adminer
      - gw_adminer_net
 
  business-logic-app:
    image: andreistan26/business-logic-service:latest
    networks:
      - gw_bl_net
      - backend_bl_net

  routes-app:
    image: andreistan26/routes-service:latest
    networks:
      - backend_routes_net
      - backend_bl_net

