version: '3.8'

networks:
  frontend_net:
    driver: overlay
  backend_net:
    driver: overlay
  adminer:
    driver: overlay


volumes:
  db_data:

services:
  db:
    image: andreistan26/database:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin  # Test
      POSTGRES_PASSWORD: password123 # Test
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
      - adminer
    #deploy:
      #placement:
        #constraints: [node.role == manager]

  auth-app:
    image: andreistan26/auth-service:latest
    networks:
      - frontend_net
      - backend_net
    #deploy:
      #replicas: 2
      #placement:
        #constraints: [node.role == worker]

  kong:
    image: andreistan26/kong:latest
    ports:
      - "80:8000"
    networks:
      - frontend_net
    #deploy:
      #placement:
        #constraints: [node.role == manager]

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - adminer
