version: '3.8'

networks:
  frontend_net:
    driver: overlay
    attachable: true
  gw_auth_net:
    driver: overlay
  gw_bl_net:
    driver: overlay
  gw_adminer_net:
    driver: overlay
  backend_auth_net:
    driver: overlay
  backend_routes_net:
    driver: overlay
  backend_bl_net:
    driver: overlay
  adminer_net:
    driver: overlay
  monitoring:
    driver: overlay
    attachable: true
  logging:
    driver: overlay
  agent_network:
    driver: overlay
    attachable: true


volumes:
  db_data:
  grafana-storage:
  portainer_data:

services:
  db:
    image: andreistan26/database:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin  # Test
      POSTGRES_PASSWORD: password123 # Test
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_routes_net
      - backend_auth_net
      - adminer_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5

    #deploy:
      #placement:
        #constraints: [node.role == manager]

  auth-app:
    image: andreistan26/auth-service:latest
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-external-labels: job=auth-app,owner=train-tickets,environment=development
    networks:
      - gw_auth_net
      - backend_auth_net
      - logging
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
    #deploy:
      #replicas: 2
      #placement:
        #constraints: [node.role == worker]

  kong:
    image: andreistan26/kong:latest
    ports:
      - target: 8022     # Testing port
        published: 8022
        protocol: tcp
        mode: host
      - 8000:8000
      - 8001:8001
    networks:
      - frontend_net
      - gw_auth_net
      - gw_bl_net
      - gw_adminer_net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
    #deploy:
      #placement:
        #constraints: [node.role == manager]

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - adminer_net
      - gw_adminer_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
 
  business-logic-app:
    image: andreistan26/business-logic-service:latest
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-external-labels: job=bl-app,owner=train-tickets,environment=development
    networks:
      - gw_bl_net
      - backend_bl_net
      - logging
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5

  routes-app:
    image: andreistan26/routes-service:latest
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-external-labels: job=routes-app,owner=train-tickets,environment=development
    networks:
      - backend_routes_net
      - backend_bl_net
      - logging
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5

  prometheus:
    image: prom/prometheus
    volumes:
        - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - 9090:9090
    networks:
        - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]

      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5

  node_exporter:
    image: prom/node-exporter
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
        - 9100:9100
    networks:
        - monitoring
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
      - logging
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5

  loki:
    image: grafana/loki
    volumes:
      - ./configs/loki.yml:/etc/config/loki.yml
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yml
    ports:
      - 3100:3100
    networks:
      - logging
      - monitoring
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5

  agent:
    image: portainer/agent:2.11.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.11.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8095:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]



