apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: andreistan26/auth-service:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app
spec:
  selector:
    app: auth-app
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-logic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-logic-app
  template:
    metadata:
      labels:
        app: business-logic-app
    spec:
      containers:
        - name: business-logic-app
          image: andreistan26/auth-service:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: business-logic-app
spec:
  selector:
    app: business-logic-app
  ports:
    - port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routes-app
  template:
    metadata:
      labels:
        app: routes-app
    spec:
      containers:
        - name: routes-app
          image: andreistan26/routes-service:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: routes-app
spec:
  selector:
    app: routes-app
  ports:
    - port: 5000
      targetPort: 5000
